# Generated by Django 3.0.6 on 2020-05-15 21:18

import api.models
import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200513_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='back_image',
            field=models.ImageField(null=True, storage=api.utils.OverwriteStorage(), upload_to=api.models.back_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email is already taken'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, storage=api.utils.OverwriteStorage(), upload_to=api.models.photo_image_path),
        ),
    ]
